version: '3.3'

services:
  bot:
    container_name: ${PROJECT_NAME}-bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 src/bot.py
    restart: always
    depends_on:
      - db
      - cache
    env_file: .env
    networks:
      - tg_bot

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: ${PROJECT_NAME}-db
    env_file: .env
    ports:
      - 5432:5432

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis_data:/data

networks:
  tg_bot:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
